site_name: DECODE DATA
site_url: https://decodedata.io/

theme:
  name: material
  font:
    text: Inter
  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny 
        name: Dark mode
      primary: white
      accent:  blue grey 
    - scheme: slate 
      toggle:
        icon: material/weather-night 
        name: Light mode    
      primary: black
      accent: cyan
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true

copyright: Copyright &copy; 2024 DECODE DATA LTD (15503524), UK