site_name: DECODE DATA
site_url: https://decodedata.io/

theme:
  name: material
  custom_dir: overrides
  font:
    text: Inter
  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny 
        name: Switch to dark mode
      primary: white
      accent:  blue grey 
    - scheme: slate 
      toggle:
        icon: material/weather-night 
        name: Switch to light mode    
      primary: black
      accent: cyan
  icon:
    repo: fontawesome/brands/github
  logo: assets/logos/Decode Data Logo 180x180.png
  favicon: assets/logos/Decode Data Logo Transparent 130x130.png
  features:
    - navigation.footer
    - navigation.indexes 
    - content.code.copy    

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true

extra:
  analytics:
    provider: google
    property: G-B2XB0TB3ZR
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

nav:
  - Overview: index.md
  - Decoders:
    - Google Analytics 4:
      - GA4 Overview: ga4/index.md
      - Quickstart: ga4/quickstart.md
      - Events: 
        - Events Overview: ga4/events/index.md
        - Names: ga4/events/event_names.md
        - Parameters: ga4/events/event_parameters.md
      - Sessions: ga4/sessions.md
      - Advanced: ga4/advanced.md
  - BigQuery Reference:
    - Functions: bigquery/functions.md

copyright: >-
  Copyright &copy; 2024 DECODE DATA LTD (15503524), UK
  <br><a href="#__consent">Change cookie settings</a>
  