site_name: DECODE DATA
site_url: https://decodedata.io/

theme:
  name: material
  font:
    text: Inter
  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny 
        name: Switch to dark mode
      primary: white
      accent:  blue grey 
    - scheme: slate 
      toggle:
        icon: material/weather-night 
        name: Switch to light mode    
      primary: black
      accent: cyan
  icon:
    repo: fontawesome/brands/github
  logo: assets/logos/Decode Data Logo 180x180.png
  favicon: assets/logos/Decode Data Logo Transparent 130x130.png
  features:
    - navigation.indexes 


markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true


nav:
  - Overview: index.md
  - Google Anaytics 4:
    - Overview: GA4/index.md
    - Events: GA4/events.md

copyright: Copyright &copy; 2024 DECODE DATA LTD (15503524), UK